### ISSUE TITLE
Wrong map Tileset causes program crash

### ISSUE THREAD

**Issue by ZERO-A-ONE** [Warzone2100/maptools-cli#13]
The constructed exception map will cause the program execution `guessMapTileset` to crash

The error message is shown below：

```bash
syc@ubuntu:~/Music/maptools-cli-1.0.4/build$ ./maptools package genpreview -i /home/syc/Music/maptools-cli-1.0.4/build/crash/2.wz -o /home/syc/Downloads/maptools-cli-1.0.4/build/t.png
INFO: [operator():1223] Map folder file: dinit.bjo
INFO: [operator():1223] Map folder file: droid.ini
INFO: [operator():1223] Map folder file: feat.bjo
INFO: [operator():1223] Map folder file: feature.ini
INFO: [operator():1223] Map folder file: game.map
INFO: [operator():1223] Map folder file: struct.bjo
INFO: [operator():1223] Map folder file: struct.ini
INFO: [operator():1223] Map folder file: ttypes.ttp
INFO: [loadTerrainTypes:42] Loading: multiplay/maps/2c-GrassyPatch/ttypes.ttp
WARNING: [loadTerrainTypes:94] multiplay/maps/2c-GrassyPatch/ttypes.ttp: Unexpectedly did not reach end of stream - data may be corrupted
UndefinedBehaviorSanitizer:DEADLYSIGNAL
==3940670==ERROR: UndefinedBehaviorSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000485763 bp 0x0000018a0c20 sp 0x7ffc67dc0800 T3940670)
==3940670==The signal is caused by a READ memory access.
==3940670==Hint: address points to the zero page.
    #0 0x485763 in guessMapTileset(WzMap::Map&) /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:282:6
    #1 0x485763 in generateMapPreviewPNG_FromMapObject(WzMap::Map&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:324:26
    #2 0x484f59 in generateMapPreviewPNG_FromPackageContents(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, std::shared_ptr<WzMap::IOProvider>) /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:381:9
    #3 0x4843c3 in generateMapPreviewPNG_FromArchive(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool) /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:394:9
    #4 0x4843c3 in addSubCommand_Package(CLI::App&, int&, bool&)::$_3::operator()() const /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:727:9
    #5 0x4843c3 in std::_Function_handler<void (), addSubCommand_Package(CLI::App&, int&, bool&)::$_3>::_M_invoke(std::_Any_data const&) /usr/lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/std_function.h:300:2
    #6 0x49f71d in CLI::App::run_callback(bool, bool) /home/syc/Music/maptools-cli-1.0.4/3rdparty/CLI11/CLI11.hpp:7251:23
    #7 0x49f71d in CLI::App::run_callback(bool, bool) /home/syc/Music/maptools-cli-1.0.4/3rdparty/CLI11/CLI11.hpp:7251:23
    #8 0x43f451 in CLI::App::parse(std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) /home/syc/Music/maptools-cli-1.0.4/3rdparty/CLI11/CLI11.hpp:6591:9
    #9 0x43f451 in CLI::App::parse(int, char const* const*) /home/syc/Music/maptools-cli-1.0.4/3rdparty/CLI11/CLI11.hpp:6519:9
    #10 0x4346d4 in main /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:888:2
    #11 0x7efc55829082 in __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:308:16
    #12 0x40b26d in _start (/home/syc/Music/maptools-cli-1.0.4/build/maptools+0x40b26d)

UndefinedBehaviorSanitizer can not provide additional info.
SUMMARY: UndefinedBehaviorSanitizer: SEGV /home/syc/Music/maptools-cli-1.0.4/src/maptools.cpp:282:6 in guessMapTileset(WzMap::Map&)
==3940670==ABORTING
```

**Comment by past-due** [comment]
Thank you for the report! We'll issue a new release soon.
